name: Simple Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target_arch:
        description: 'Target architecture'
        required: false
        default: 'linux/amd64'
        type: choice
        options:
        - linux/amd64
        - linux/arm64

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ${{ (github.event.inputs.target_arch || 'linux/amd64') == 'linux/amd64' && 'python:3.12-slim' || null }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      if: ${{ (github.event.inputs.target_arch || 'linux/amd64') != 'linux/amd64' }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: Lint with pylint
      run: |
        pylint --exit-zero *.py

  style:
    runs-on: ubuntu-latest
    container: ${{ (github.event.inputs.target_arch || 'linux/amd64') == 'linux/amd64' && 'python:3.12-slim' || null }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      if: ${{ (github.event.inputs.target_arch || 'linux/amd64') != 'linux/amd64' }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    
    - name: Check code formatting with black
      run: |
        black --check --diff .
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .

  type-check:
    runs-on: ubuntu-latest
    container: ${{ (github.event.inputs.target_arch || 'linux/amd64') == 'linux/amd64' && 'python:3.12-slim' || null }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      if: ${{ (github.event.inputs.target_arch || 'linux/amd64') != 'linux/amd64' }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    
    - name: Type check with mypy
      run: |
        mypy --ignore-missing-imports *.py

  test:
    runs-on: ubuntu-latest
    container: ${{ (github.event.inputs.target_arch || 'linux/amd64') == 'linux/amd64' && 'python:3.12-slim' || null }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      if: ${{ (github.event.inputs.target_arch || 'linux/amd64') != 'linux/amd64' }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: |
        python3 -m pytest test_trie.py -v 